name: co.appdaddy.fml
#package name must be co.appdaddy.fml for play store, dev.fml for play store.
version: 3.3.3+26
description: Framework Markup Language
homepage: https://fml.dev
repository: https://github.com/AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language.git

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  fml:
    path: ../

dev_dependencies:

  # Dart linter
  lints: ^3.0.0

  # Flutter linter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/applications/

    - assets/applications/example/
    - assets/applications/example/images/
    - assets/applications/example/templates/

    - assets/applications/fmlpad/
    - assets/applications/fmlpad/images/
    - assets/applications/fmlpad/templates/

  fonts:
    - family: custom_icons
      fonts:
        - asset: assets/fonts/custom_icons.ttf