// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_rdRL6TQgjw7QM8rTTJeqgO8puZ73jNI',
    appId: '1:1070564786024:web:66d63da83a2a153ffce0dd',
    messagingSenderId: '1070564786024',
    projectId: 'flutter-markup-language',
    authDomain: 'flutter-markup-language.firebaseapp.com',
    storageBucket: 'flutter-markup-language.appspot.com',
    measurementId: 'G-MYW15SHGG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1H3dyW2sAGS3FiY_7eZ83D1b00rfqWa0',
    appId: '1:1070564786024:android:1e8eece69a2e5ee3fce0dd',
    messagingSenderId: '1070564786024',
    projectId: 'flutter-markup-language',
    storageBucket: 'flutter-markup-language.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtBko6G3-3PrHCNNw__pUKXDXSGrEY1pA',
    appId: '1:1070564786024:ios:df820e7e85ad4c30fce0dd',
    messagingSenderId: '1070564786024',
    projectId: 'flutter-markup-language',
    storageBucket: 'flutter-markup-language.appspot.com',
    iosBundleId: 'dev.fml',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtBko6G3-3PrHCNNw__pUKXDXSGrEY1pA',
    appId: '1:1070564786024:ios:9254a9d8559f1033fce0dd',
    messagingSenderId: '1070564786024',
    projectId: 'flutter-markup-language',
    storageBucket: 'flutter-markup-language.appspot.com',
    iosBundleId: 'dev.fml.fml',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_rdRL6TQgjw7QM8rTTJeqgO8puZ73jNI',
    appId: '1:1070564786024:web:4eedd92c08312d31fce0dd',
    messagingSenderId: '1070564786024',
    projectId: 'flutter-markup-language',
    authDomain: 'flutter-markup-language.firebaseapp.com',
    storageBucket: 'flutter-markup-language.appspot.com',
    measurementId: 'G-HFKHD9YG0W',
  );
}
